all:
	jbuilder build @DEFAULT
	echo "\nThe outputs (including index.html) go in the _build directory that's \
a couple directories up. Read more about what determined that here:\n \
http://jbuilder.readthedocs.io/en/latest/usage.html#finding-the-root\n"
	echo "\nPoint your browser to\n ${PWD}/../../_build/default/03-frogger/test-js-of-ocaml-install/index.html"
